name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test_and_build:
    runs-on: ubuntu-latest


    # det här kan läggas till om man inte använder testcontainers
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bookingdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: set up javen enviroment
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: build and run tests
        run: mvn -B package
        env:
          # om man får error här kan det vara att det ska stå localhost:3306 istället
          SPRING_DATASOURCE_URL: jdbc:mysql://booking-db:3306/bookingdb
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
